version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run: sudo apt install curl
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
      - run: sudo apt install nodejs
      - run: npm install -g ionic cordova
      - run:
          name: run build file
          command: sudo ./build.sh $CIRCLE_BRANCH
