version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run: npm install
      - run:
          name: run build file
          command: ./build.sh $CIRCLE_BRANCH
